# Common Build Properties
################################################################################

#properties used in acmrest.jar manifest
productname = IBM Business Automation Workflow Case Builder
productversion = 26.0.0
companyname = IBM Corporation
copyright = Copyright IBM Corp. 2010,2018  All rights reserved

################################################################################
# Commonly used paths
################################################################################

3pt.dir=..
apache.ant.dir=apache-ant-1.10.11
icm.schema.dir=icm-schema
ilog.rules.sdk.version=81051
ilog.rules.sdk.dir=ilog-rules-sdk
3pt.java.sdk=jdk
pageDesigner.dir=pageDesigner
propertiesDesigner.dir=propertiesDesigner
icmProperties.dir=icm-properties
icmProperties.pvd.dir=icm-properties/pvd
icmProperties.pvr.dir=icm-properties/pvr
reactintegration.dir=reactintegration

src=src
src.lib=lib
servlet.src=servlet-src

javac.args=-Xlint\:deprecation,unchecked

icm.rules.api.lib.dir=icm-rules-api/lib

output=bin

icm.solution.edit.jar=ICMSolutionEdit.jar
icm.cbproperties.jar=cbproperties.jar
icm.casebuilder.jar=CaseBuilder.jar

icm.rules.api.dir=icm-rules-api

ibmdojo.dir=ibmdojo
idx.dir=idx
findbugs.dir=findbugs/findbugs-3.0.1

jaxb22.dir=jaxb-ri-2.2
jaxb22.lib.dir=jaxb-ri-2.2/jaxb-ri/lib
