# Change ARTIFACTORY_USERNAME and ARTIFACTORY_PASSWORD and rename this file to gradle.properties.  Alternatively, the variables below can be set as system global variables instead.
# ARTIFACTORY_PASSWORD should ideally be an API Key (which you can copy from your Artifactory server profile) but can also be an ecrypted password (which you can copy from your Artifactory server profile) or a clear text password
ARTIFACTORY_URL=https\://na.artifactory.swg-devops.com/artifactory
ARTIFACTORY_USERNAME=username
ARTIFACTORY_PASSWORD=password

# Set the Gradle Daemon for faster builds after the first build
#org.gradle.daemon=true
# Set the Java home for this project (Must be IBM Java SDK 8).  If this is not set, system JAVA_HOME will be used
#org.gradle.java.home=C\:\\Users\\IBM_ADMIN\\My Documents\\git\\icm-api/ibm-java-sdk/sdk
